"""Migration profiles: one data file per version-step (e.g. v11_to_v10).

A profile holds *everything that differs* between two adjacent .spp versions --
renames, dropped fields, the target schema, data_version numbers. The Python
engine is version-agnostic and reads the active profile; to support a new step
you author a profile (mostly auto-generated by debug/build_profile.py), not code.

The only per-format code is the binary codec (parse source format / write target
format), named by `source_format` / `target_format` in the profile. We currently
ship the "registry" parser (v11) and "inline" writer (v10); older inline targets
(v9/v8) likely reuse the inline writer with only profile data changing.

Select a profile with the SPP_PROFILE env var (default: v11_to_v10).
"""
import os
import re
import json

_LIB_DIR = os.path.dirname(__file__)
_DEFAULT_PROFILE_DIR = os.path.normpath(os.path.join(_LIB_DIR, "..", "..", "profiles"))


def _resolve(name, search):
    if os.path.isabs(name):
        return name
    for d in search:
        cand = os.path.join(d, name)
        if os.path.exists(cand):
            return cand
    return os.path.join(search[0], name)  # let the open() error point at the real path


class MigrationProfile:
    def __init__(self, data, base_dir):
        self.data = data
        self.base_dir = base_dir
        search = [base_dir, _LIB_DIR]
        # schema/baking_schema can be inlined or referenced by file
        self.schema = data.get("schema")
        if self.schema is None and data.get("schema_file"):
            with open(_resolve(data["schema_file"], search), "r", encoding="utf-8") as f:
                self.schema = json.load(f)
        self.schema = {t: list(m) for t, m in (self.schema or {}).items()}
        # schema_add: hand-authored schema entries for types the auto-generated corpus
        # never sampled (e.g. DataActionSmudge -- no v8.1 sample uses the smudge tool).
        # Lives in the overrides file so generated schema files stay regenerable. Lets the
        # projection SYNTHESIZE members v8.1 requires that a newer source dropped, and drop
        # members it added -- the symmetric partner to the binary member-allowlist filter.
        for t, members in (data.get("schema_add") or {}).items():
            self.schema[t] = list(members)

        baking = data.get("baking_schema")
        if baking is None and data.get("baking_schema_file"):
            with open(_resolve(data["baking_schema_file"], search), "r", encoding="utf-8") as f:
                baking = json.load(f)
        self.baking_schema = {k: [tuple(x) for x in v] for k, v in (baking or {}).items()}

        # defaults: type -> {member: {kind, code, value(hex)}}; used to synthesize a
        # required member the source lacks (older readers error on a missing member).
        defaults = data.get("defaults")
        if defaults is None and data.get("defaults_file"):
            try:
                with open(_resolve(data["defaults_file"], search), "r", encoding="utf-8") as f:
                    defaults = json.load(f)
            except Exception:
                defaults = {}
        self.schema_defaults = defaults or {}
        # defaults_add: default values (from genuine target-version files) for the
        # synthesized members of schema_add types. Merged per-type so existing defaults win
        # only where not provided here.
        for t, defs in (data.get("defaults_add") or {}).items():
            self.schema_defaults.setdefault(t, {}).update(defs)

    @property
    def type_rename(self):
        return self.data.get("type_rename", {})

    @property
    def baking_tweak_rename(self):
        return self.data.get("baking_tweak_rename", {})

    @property
    def baking_baker_id_rename(self):
        return self.data.get("baking_baker_id_rename", {})

    @property
    def field_rename(self):
        """{'Type.oldfield': 'newfield'} (or bare 'oldfield': 'newfield' global)."""
        return self.data.get("field_rename", {})

    @property
    def field_retype(self):
        """{'Type.field': target_primitive_code} -- a field whose primitive type/width
        changed across versions (e.g. channelTypes 16B->8B). Engine resizes the value."""
        return self.data.get("field_retype", {})

    @property
    def field_rekind(self):
        """{'Type.field': 'array'|'object'} -- a field that changed container kind
        (e.g. sourceTransparent object->array). Engine wraps/unwraps the value."""
        return self.data.get("field_rekind", {})

    @property
    def field_value_transform(self):
        """{'Type.field': {'op': 'enum_to_bitmask', 'code': N}} -- a field whose VALUE
        semantics changed (e.g. DataChannel.type: enum index n -> bitmask 1<<n)."""
        return self.data.get("field_value_transform", {})

    @property
    def primitive_retype(self):
        """{old_code: new_code} applied BLANKETLY to every primitive of old_code anywhere
        (e.g. v12.1 added code 22 / 128-bit channel masks; older versions need 22->12,
        truncated). Catches occurrences the per-field field_retype map never sampled."""
        return {int(k): int(v) for k, v in self.data.get("primitive_retype", {}).items()}

    @property
    def blacklist(self):
        return list(self.data.get("blacklist", []))

    @property
    def data_version_map(self):
        return self.data.get("data_version_map", {})

    @property
    def dataset_renames(self):
        return self.data.get("dataset_renames", {})

    @property
    def target_max_data_version(self):
        return int(self.data.get("target_max_data_version", 0))


def _merge_override(base, ov):
    """Deep-merge a hand-authored override onto an auto-generated base: dicts merge
    key-wise (override wins), lists union (preserving order), scalars override."""
    for k, v in ov.items():
        if isinstance(v, dict) and isinstance(base.get(k), dict):
            _merge_override(base[k], v)
        elif isinstance(v, list) and isinstance(base.get(k), list):
            base[k] = base[k] + [x for x in v if x not in base[k]]
        else:
            base[k] = v
    return base


def _load_path(path):
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    # A sibling <name>.overrides.json carries hand-authored knowledge so the base
    # profile stays freely regenerable by automap. Overrides win / extend.
    ov_path = path[:-5] + ".overrides.json" if path.endswith(".json") else path + ".overrides.json"
    if os.path.exists(ov_path):
        try:
            with open(ov_path, "r", encoding="utf-8") as f:
                data = _merge_override(data, json.load(f))
        except Exception:
            pass
    return MigrationProfile(data, os.path.dirname(os.path.abspath(path)))


def _load_one(name, profile_dir):
    path = name if name.endswith(".json") else os.path.join(profile_dir, name + ".json")
    return _load_path(path)


def _compose_rename(d1, d2):
    """Compose two rename maps applied in order (d1 then d2): A->B->C yields A->C."""
    out = {k: d2.get(v, v) for k, v in d1.items()}
    for k, v in d2.items():
        out.setdefault(k, v)
    return out


def _compose(chain):
    """Collapse an ordered chain of adjacent-step profiles into one effective
    profile. Transforms run on the decoded tree, so the chain is equivalent to:
    compose renames transitively, union blacklists, project to the LAST target's
    schema/versions. No per-pair file needed -- any pair composes from the links."""
    if len(chain) == 1:
        return chain[0]
    last = chain[-1]
    merged = dict(last.data)
    merged.pop("schema", None)
    merged.pop("baking_schema", None)
    merged["from"] = chain[0].data.get("from")
    merged["source_format"] = chain[0].data.get("source_format")
    bl = []
    for step in chain:
        for x in step.blacklist:
            if x not in bl:
                bl.append(x)
    merged["blacklist"] = bl
    for key in ("type_rename", "baking_tweak_rename", "baking_baker_id_rename", "dataset_renames", "field_rename"):
        acc = {}
        for step in chain:
            acc = _compose_rename(acc, step.data.get(key, {}))
        merged[key] = acc
    # field_retype/field_rekind/field_value_transform/primitive_retype aren't names -> last-wins
    for key in ("field_retype", "field_rekind", "field_value_transform", "primitive_retype"):
        acc = {}
        for step in chain:
            acc.update(step.data.get(key, {}))
        merged[key] = acc
    eff = MigrationProfile(merged, last.base_dir)
    eff.schema = last.schema            # project straight to final target
    eff.baking_schema = last.baking_schema
    eff.schema_defaults = last.schema_defaults
    return eff


def _vkey(label, pad=0):
    parts = [int(x) for x in label.split(".")]
    while len(parts) < 3:
        parts.append(pad)
    return tuple(parts[:3])


def _snap_target(to, edges):
    """Snap a requested target version DOWN to the nearest version we actually have a
    transform for. Minor versions within a major share the file format, and forward-
    compatibility is free (a newer Painter opens an older file), so a file built for the
    nearest lower boundary opens in the requested (higher) version. This means we cover
    every minor (8.1, 8.2, 8.3, ...) with just the major-boundary maps -- no per-minor
    transforms. A bare major ('8') matches any of its minors."""
    nodes = set(edges)
    for d in edges.values():
        nodes.update(d)
    if to in nodes:
        return to
    tk = _vkey(to, pad=999)   # bare/partial target matches the highest minor in that major
    fits = [n for n in nodes if _vkey(n) <= tk]
    return max(fits, key=_vkey) if fits else to


def _snap_source(frm, edges):
    nodes = set(edges)
    for d in edges.values():
        nodes.update(d)
    if frm in nodes:
        return frm
    fk = _vkey(frm, pad=999)
    fits = [n for n in nodes if _vkey(n) <= fk and _vkey(n)[0] == fk[0]]
    return max(fits, key=_vkey) if fits else frm


def _discover_edges(profile_dir):
    """Map of adjacent steps available on disk: {from_label: {to_label: path}}.
    Version labels may be dotted (e.g. '8.1'), so this is a graph, not an int range."""
    import glob as _glob
    edges = {}
    for path in _glob.glob(os.path.join(profile_dir, "v*_to_v*.json")):
        base = os.path.basename(path)
        if base.endswith(".overrides.json"):   # sibling override files are not edges
            continue
        m = re.fullmatch(r"v(.+?)_to_v(.+)", base[:-5])
        if m:
            edges.setdefault(m.group(1), {})[m.group(2)] = path
    return edges


def _major_baseline_profile(major, profile_dir=None):
    profile_dir = profile_dir or os.environ.get("SPP_PROFILE_DIR", _DEFAULT_PROFILE_DIR)
    edges = _discover_edges(profile_dir)
    requested = str(major)
    requested_key = _vkey(requested)
    requested_major = requested_key[0] if requested_key else None
    targets = sorted({to for tos in edges.values() for to in tos}, key=_vkey)
    if requested in targets:
        target = requested
    else:
        fits = [t for t in targets if requested_major is not None and _vkey(t)[0] == requested_major]
        target = max(fits, key=_vkey) if fits else requested
    sources = sorted((frm for frm, tos in edges.items() if target in tos), key=_vkey)
    if not sources:
        return None
    prof = _load_path(edges[sources[0]][target])
    supported = _target_sample_types()
    if supported:
        kept = [t for t in prof.data.get("blacklist", []) if t not in supported]
        if kept != prof.data.get("blacklist", []):
            prof.data = dict(prof.data, blacklist=kept)
    return prof


_SAMPLE_TYPES_CACHE = {}


def _target_sample_types():
    exe = os.environ.get("SPP_TARGET_BINARY")
    if not exe:
        return frozenset()
    if exe in _SAMPLE_TYPES_CACHE:
        return _SAMPLE_TYPES_CACHE[exe]
    found = set()
    try:
        import glob as _glob, struct as _struct
        import h5py
        from lib.hbo_reserializer.serializer import HBOSerializer
        samples = os.path.join(os.path.dirname(exe), "resources", "samples")
        for path in _glob.glob(os.path.join(samples, "*.spp")):
            try:
                f = h5py.File(path, "r")
            except Exception:
                continue
            def _visit(_n, o):
                if not isinstance(o, h5py.Dataset):
                    return
                try:
                    raw = bytes(o[()])
                except Exception:
                    return
                if len(raw) < 12 or _struct.unpack("<III", raw[:12])[1] != 1:
                    return
                try:
                    for d in HBOSerializer(raw).registry_defs:
                        if d.get("name"):
                            found.add(d["name"])
                except Exception:
                    pass
            f.visititems(_visit)
            f.close()
    except Exception:
        found = set()
    result = frozenset(found)
    _SAMPLE_TYPES_CACHE[exe] = result
    return result


def _find_path(edges, frm, to):
    """BFS the adjacent-step graph for a downgrade chain frm -> ... -> to.
    Returns the ordered list of step file paths, or None."""
    from collections import deque
    q = deque([(frm, [])])
    seen = {frm}
    while q:
        cur, steps = q.popleft()
        if cur == to:
            return steps
        # prefer descending next-hops for determinism
        for nxt in sorted(edges.get(cur, {}), key=_vkey, reverse=True):
            if nxt not in seen:
                seen.add(nxt)
                q.append((nxt, steps + [edges[cur][nxt]]))
    return None


def load(name=None):
    """Load a profile by name (default from SPP_PROFILE env, else v11_to_v10).

    Only *adjacent* step files exist on disk (v11_to_v10, v10_to_v9, v9_to_v8.1, ...).
    A request for a non-adjacent pair (e.g. v12_to_v8.1) is composed by walking the
    adjacent-step graph and chaining the links -- no per-pair file required. Version
    labels may be dotted; gaps are fine as long as adjacent steps connect end to end."""
    name = name or os.environ.get("SPP_PROFILE", "v11_to_v10")
    profile_dir = os.environ.get("SPP_PROFILE_DIR", _DEFAULT_PROFILE_DIR)

    direct = os.path.join(profile_dir, name if name.endswith(".json") else name + ".json")
    if os.path.exists(direct):
        return _load_one(name, profile_dir)        # an explicit/adjacent file wins

    m = re.fullmatch(r"v(.+?)_to_v(.+)", os.path.basename(name).replace(".json", ""))
    if not m:
        return _load_one(name, profile_dir)         # not a pair name -> let open() error
    frm, to = m.group(1), m.group(2)
    edges = _discover_edges(profile_dir)
    snapped_from = _snap_source(frm, edges)
    snapped = _snap_target(to, edges)
    path = _find_path(edges, snapped_from, snapped)
    if not path:
        if path == [] and snapped_from == snapped and _vkey(frm)[0] == _vkey(to)[0] and _vkey(frm) > _vkey(to):
            baseline = _major_baseline_profile(to, profile_dir)
            if baseline is not None:
                return baseline
        if path is None and _vkey(frm)[0] == _vkey(to)[0] and _vkey(frm) > _vkey(to):
            baseline = _major_baseline_profile(to, profile_dir)
            if baseline is not None:
                return baseline
        return _load_one(name, profile_dir)         # no chain -> clear error
    chain = [_load_path(p) for p in path]
    return chain[0] if len(chain) == 1 else _compose(chain)


def derive_introductions(profile_dir=None):
    """{feature_name: earliest_version_label_it_was_introduced} derived from the per-step
    blacklists already on disk -- DRY, no parallel hand-authored file to keep in sync.

    A feature blacklisted in v{FROM}_to_v{TO} exists in FROM but not TO, i.e. it was
    introduced at FROM. A feature can appear in several steps; we keep the LOWEST FROM
    (earliest appearance). A sibling `feature_introduction.overrides.json` (same
    base+overrides idiom as the profiles) can add/correct entries -- overrides win.
    """
    profile_dir = profile_dir or os.environ.get("SPP_PROFILE_DIR", _DEFAULT_PROFILE_DIR)
    edges = _discover_edges(profile_dir)
    intro = {}
    for frm, tos in edges.items():
        for _to, path in tos.items():
            try:
                with open(path, "r", encoding="utf-8") as f:
                    data = json.load(f)
            except Exception:
                continue
            for feat in data.get("blacklist", []):
                cur = intro.get(feat)
                if cur is None or _vkey(frm) < _vkey(cur):
                    intro[feat] = frm
    ov = os.path.join(profile_dir, "feature_introduction.overrides.json")
    if os.path.exists(ov):
        try:
            with open(ov, "r", encoding="utf-8") as f:
                intro.update(json.load(f).get("introductions", {}))
        except Exception:
            pass
    return intro


def blend_max_for(target_label, profile_dir=None):
    """Highest blendingMode enum the target version supports, from
    feature_introduction.overrides.json's `blend_max_by_version`, or None if unknown
    (which disables blend-mode classification -- safe: nothing gets composited)."""
    profile_dir = profile_dir or os.environ.get("SPP_PROFILE_DIR", _DEFAULT_PROFILE_DIR)
    ov = os.path.join(profile_dir, "feature_introduction.overrides.json")
    try:
        with open(ov, "r", encoding="utf-8") as f:
            table = json.load(f).get("blend_max_by_version", {})
    except Exception:
        return None
    if target_label in table:
        return int(table[target_label])
    # fall back to the highest entry <= target (a minor shares its major's modes)
    tk = _vkey(target_label)
    fits = [(k, v) for k, v in table.items() if _vkey(k) <= tk]
    return int(max(fits, key=lambda kv: _vkey(kv[0]))[1]) if fits else None


def feature_floor(supported_versions):
    """Lowest label in `supported_versions` -> features introduced at/below it need no
    fallback (every supported target already has them). None if the list is empty."""
    labels = [v for v in (supported_versions or []) if _vkey(v)]
    return min(labels, key=_vkey) if labels else None


def above_floor(intro_label, floor_label):
    """True if a feature introduced at `intro_label` is newer than `floor_label`
    (so it is a bake-fallback candidate at pack time, where the target is unknown)."""
    if not intro_label or not floor_label:
        return bool(intro_label)  # unknown floor -> treat everything as above it
    return _vkey(intro_label) > _vkey(floor_label)


# Active profile, loaded once. Falls back to an empty profile so a missing file
# degrades to no-op transforms rather than crashing at import.
try:
    ACTIVE = load()
except Exception as _e:  # pragma: no cover - diagnostic only
    import sys
    print(f"[migration_profile] WARNING: no profile loaded ({_e}); transforms disabled", file=sys.stderr)
    ACTIVE = MigrationProfile({}, _DEFAULT_PROFILE_DIR)
